use_frameworks!

target 'JGNavigationBarTransition_Example' do
#  pod 'JGNavigationBarTransition', :path => '../'

  target 'JGNavigationBarTransition_Tests' do
#    inherit! :search_paths

    
  end
end
