use_frameworks!

platform :ios, '8.0'

target 'JGNavigationBarTransition_Example' do
  pod 'JGNavigationBarTransition', :path => '../'

  target 'JGNavigationBarTransition_Tests' do
    inherit! :search_paths

    
  end
end
